# 超像素前的高斯模糊操作
gaussian_blur:
  # 高斯核尺寸
  ksize: [3, 3]
  sigmaX: 0
  sigmaY: 0

# 超像素算法，可以是 SLIC 或 SEED
superpixel_algorithm: "SEED"

slic:
  # 超像素大小，决定了超像素数量（= 原像素数量 / 超像素大小）
  region_size: 32
  # 使用哪种 SLIC 算法变体，包括：SLIC、SLICO（默认）、MSLIC
  algorithm: SLICO
  # SLIC 迭代次数
  num_iterations: 100

seed:
  # 超像素数量
  num_superpixels: 2000
  num_levels: 20
  prior: 3
  histogram_bins: 5
  # SEED 迭代次数
  num_iterations: 100

kmeans:
  # 聚类数目（K）
  nclusters: 5
  
  # 尝试次数，使用结果最好的一次
  attempts: 100

  # 终止条件
  criteria:
    # 终止条件类型，包括：
    # 1. TERM_CRITERIA_EPS：簇心变动幅度低于 epsilon 时终止
    # 2. TERM_CRITERIA_MAX_ITER：达到最大迭代次数时终止
    # 可叠加 - "TERM_CRITERIA_EPS+TERM_CRITERIA_MAX_ITER"
    type: TERM_CRITERIA_EPS+TERM_CRITERIA_MAX_ITER
    # 最大迭代次数
    max_iter: 100000
    # 簇心变动幅度
    epsilon: 0.000001
  
  # K-Means 初始化簇心的方法，包括：
  # 1. KMEANS_PP_CENTERS：按照 K-Means++ 论文中的方法
  # 2. KMEANS_RANDOM_CENTERS：随机初始化
  flags: KMEANS_PP_CENTERS

contour:
  # 提取轮廓层级的模式，包括：
  # 1. RETR_EXTERNAL：只提取最外部轮廓
  # 2. RETR_LIST：提取所有轮廓，但不建立父子和嵌套关系
  # 3. RETR_CCOMP：提取所有轮廓，并组织为两个层级的关系
  # 4. RETR_TREE：提取所有轮廓，并包含完成的层级关系
  retrieval_mode: RETR_TREE
  # 提取轮廓点的模式，包括：
  # 1. CHAIN_APPROX_NONE：存储所有轮廓点
  # 2. CHAIN_APPROX_SIMPLE：只存储必要的轮廓点以节省空间，比如矩形只需要四个顶点
  approx_mode: CHAIN_APPROX_SIMPLE
  # 轮廓线粗细
  line_thickness: 2

# 限制最小区域尺寸，低于该尺寸的区域将被过滤
min_area: 4096

# 轮廓线颜色
contour_color: [200, 200, 200]

# 是否在图片底部展示颜色面板
show_bottom_panel: true